import './globals.css'
import type { Metadata } from 'next'
import { roboto } from '@/theme/fonts'
import Providers from '@/providers/Providers'

export const metadata: Metadata = {
	title: 'Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='ru'>
			<Providers>
				<body className={roboto.className}>
					<main>{children}</main>
				</body>
			</Providers>
		</html>
	)
}
